### ISSUE TITLE
Manually load 'string'

### ISSUE THREAD

**Issue by Toverbal** [coderifous/jquery-localize#18]
I guess this is more a feature request, but I'll post it here anyway :). I need to localize a web page, but it does not only contain html elements that need translation, there are also some dynamic div's, alerts and prompts. From what I have read it is not possible to do something like loading the localization normally (which localizes all elements on the page) and then after they are loaded use e.g. alert($.localize.load("msg_are_you_sure")) , which will use the last loaded localization. I figured I could use hidden inputs to store all these messages, but the approach I suggested might be more comfortable.

I'm sorry if I overlooked an existing feature here...

**Comment by costales** [comment]
Hi @coderifous.
How can I do that if the translations file are in a subdirectory?

This is not working by the "/":

	<script>
		$("[data-localize]").localize("locales/messages", { language: "es" });
		console.log($.localize.data.locales/messages.search);
	</script>

In the root path is working (But I'd like the messages in a subdirectory):

	<script>
		$("[data-localize]").localize("messages", { language: "es" });
		console.log($.localize.data.messages.search);
	</script>

Thanks in advance and for your great plugin!

**Comment by costales** [comment]
I'm so sorry :) I found it:

		console.log($.localize.data["locales/messages"]["My String"]);

A hug and thanks again :)

**Comment by RobertKolman** [comment]
Thanks a lot. I could not find it more than an hour. You are my hero :D
