### ISSUE TITLE
Default text fallback

### ISSUE THREAD

**Issue by moander** [coderifous/jquery-localize#21]
Hi.

I am testing out this library and it seems to be perfect for my use. I just have one little problem. When I translate to a language that does not exist, the default values are used instead. But when I translate to a language where a language file exists, but not all the keys, the default value is ignored and a empty value is inserted instead. Is there a way to force the default values to be used instead of an empty string?

**Comment by coderifous** [comment]
I believe this was fixed by issue #37.
