### ISSUE TITLE
Ajax complete

### ISSUE THREAD

**Issue by nikmauro** [coderifous/jquery-localize#39]
Hello it's possible to re-initialize the localize after a request ajax complete or load event?

example not working

```javascript
$(document).ajaxStop(function(){
	var opts = { language: "en", pathPrefix: "/" };
	$("[data-localize]").localize("shop", opts);
});
```

**Comment by LucasVandroux** [comment]
I'm also looking for a way to do so.

**Comment by coderifous** [comment]
The library itself shouldn't care about when it's invoked.  I can't think of any particular reason this would be a problem.
