### ISSUE TITLE
the plugin can not work ,run testcase 2 fail,run example language_and_country.html also failed

### ISSUE THREAD

**Issue by cucr** [coderifous/jquery-localize#44]
![qq 20141029163457](https://cloud.githubusercontent.com/assets/3097560/4822756/6c825bde-5f46-11e4-8d8f-e746b6827769.jpg)

![qq 20141029163916](https://cloud.githubusercontent.com/assets/3097560/4822786/ff6685ce-5f46-11e4-8eda-ca85011845ae.jpg)

**Comment by Haixing-Hu** [comment]
seems that the test case should be run in a web server.

**Comment by coderifous** [comment]
Test passes fine.
