### ISSUE TITLE
This library does not work on IE or Google

### ISSUE THREAD

**Issue by jaska45** [coderifous/jquery-localize#45]
I made a small test and noticed that it only works when run on Firefox on Windows 8.1. When using IE or Crome the library crashes. I cannot even run the test cases you provide but almost all tests fail.

**Comment by coderifous** [comment]
This must be a problem with your setup or something.  All tests are passing.

**Comment by AlexandreCH** [comment]
Hello, what do you think could be a problem, all tests provided fail on IE or Chrome? Thanks in advance
