### ISSUE TITLE
Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by ivoputzer** [coderifous/jquery-localize#53]
Synchronous XMLHttpRequest on the main thread are being deprecated because of its detrimental effects to the end user's experience. Recent browser versions are deprecating jQuery's async flag. It would be good thing to remove them.

![screen shot 2015-07-28 at 12 56 23](https://cloud.githubusercontent.com/assets/1570449/8929782/211bf944-3528-11e5-9530-7d782266bb04.png)

**Comment by htsnet** [comment]
I am receiving the same message on my app. What I can do to avoid this error?

**Comment by ivoputzer** [comment]
as of today browsers are already deprecating this flag; hope the pr gets merged

**Comment by Skyost** [comment]
:+1:

**Comment by coderifous** [comment]
Should be fixed by https://github.com/coderifous/jquery-localize/commit/d55b25fd6655549502b83304fadb7b47c7124940
