### ISSUE TITLE
How to clear local storage when .json file changes on production

### ISSUE THREAD

**Issue by nitinsurana** [coderifous/jquery-localize#70]
Hi,

We made some enhancements, but they are not reflecting on production for many users, because localStorage is not cleared.
I thought of adding some `?_=` param to `.json` path but could not find `pathSuffix` or something similar.

How to achieve this ?

**Comment by alvin0618** [comment]
Add `?v=' + Math.random(),` into ajaxOption
```
      ajaxOptions = {
        url: file + '?v=' + Math.random(),
        dataType: "json",
        async: false,
        timeout: options.timeout != null ? options.timeout : 500,
        success: successFunc,
        error: errorFunc
      };
```

**Comment by balazsnemeth** [comment]
This is wokring without changing the internal library code:

```
var translationOptions = { language: "de", fileExtension: ('json'+ '?v=' + Math.random())};
$("[data-localize]").localize("home", translationOptions);
```
